myblog/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<int:post_id>/', views.post_detail, name='post_detail'),
    path('search/', views.search, name='search'),
    path('archives/<int:year>/<int:month>/', views.archives, name='archives'),
    path('add_post/', views.add_post, name='add_post')
]

myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from utils.upload import upload_file


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('blog.urls')),
    # path('uploads/', upload_file, name='uploads')   # 上传图片url
    path('ckeditor/', include('ckeditor_uploader.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myblog/users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path('login/', views.login_view, name="login"),
    path('forget_pwd/', views.forget_pwd, name='forget_pwd'),
    path('logout/', views.logout_view, name='logout'),
    path('reset_pwd/<code>/', views.reset_pwd, name='reset_pwd'),
    path('reset_pwd_inner/', views.reset_pwd_inner, name='reset_pwd_inner'),
    path('user_profile/', views.user_profile, name='user_profile'),
    path('editor_users/', views.editor_users, name='editor_users')
]

myblog/users/models.py
from django.db import models
# Django内置用户user模型
from django.contrib.auth.models import User

from django.utils import timezone


class UserProfile(models.Model):
    """ 用户模型，继承并扩展Django内置User模型 """
    owner = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='用户')
    desc = models.TextField('个人简介', max_length=200, blank=True, default='')
    sign = models.TextField('个性签名', max_length=200, blank=True, default='')
    image = models.ImageField(upload_to='images/%Y/%m', default='images/default.png', max_length=100, verbose_name='用户头像')

    class Meta:
        verbose_name = "用户信息"
        verbose_name_plural = verbose_name
    
    def __str__(self):
        return self.owner.username


class EmailVerifyRecord(models.Model):
    code = models.CharField('验证码', max_length=6)
    email = models.EmailField('邮箱', max_length=35)
    ge_date = models.DateTimeField('生成时间', null=False, blank=True, default=timezone.now)

    class Meta:
        verbose_name = '邮箱验证码'
        verbose_name_plural = verbose_name
        
    def __str__(self):
        return self.code

myblog/users/forms.py
from django import forms

from django.contrib.auth.models import User
from users.models import UserProfile
from django.core.exceptions import ValidationError


class LoginForm(forms.Form):
    """ 登录表单 """
    
    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(auto_id=False, *args, **kwargs)
    
    username = forms.CharField(label='', max_length=22,  widget=forms.TextInput(attrs={
        'class': 'input',
        'placeholder': '用户名/邮箱'
    }))
    password = forms.CharField(label='', min_length=5, widget=forms.PasswordInput(attrs={
        'class': 'input',
        'placeholder': '密码'
    }))


class ForgetForm(forms.Form):
    """ 忘记密码表单 """

    def __init__(self, *args, **kwargs):
        super(ForgetForm, self).__init__(auto_id=False, *args, **kwargs)

    email = forms.EmailField(label='', min_length=4, widget=forms.EmailInput(attrs={
        'class': 'input',
        'placeholder': '请输入注册邮箱地址'
    }))


class ModifyPwdForm(forms.Form):
    """ 修改密码表单 """

    def __init__(self, *args, **kwargs):
        super(ModifyPwdForm, self).__init__(auto_id=False, *args, **kwargs)

    password = forms.CharField(label='', min_length=5, widget=forms.PasswordInput(attrs={
                'class': 'input',
                'placeholder': '请输入新密码'
    }))
    password2 = forms.CharField(label='', min_length=5, widget=forms.PasswordInput(attrs={
        'class': 'input',
        'placeholder': '请再次输入密码'
    }))

    def clean_password2(self):
        """ 检查两次输入的密码是否一致 """
        if self.cleaned_data['password2'] != self.cleaned_data['password']:
            raise forms.ValidationError("两次输入的密码不一致！")
        return self.cleaned_data['password']


class ModifyUserForm(forms.ModelForm):
    """ 修改用户信息表单 """
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'class': 'input'
    }))
    username = forms.CharField(label='用户名', widget=forms.TextInput(attrs={
        'class': 'input'
    }))

    class Meta:
        model = User
        fields = ('email', 'username')
    

class ModifyUserProfileForm(forms.ModelForm):
    
    desc = forms.CharField(label='个人简介', widget=forms.TextInput(attrs={
        'class': 'input'
    }))
    sign = forms.CharField(label='个性签名', widget=forms.TextInput(attrs={
        'class': 'input'
    }))

    class Meta:
        model = UserProfile
        fields = ('desc', 'sign', 'image')

myblog/users/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.backends import ModelBackend   # django默认身份验证后端
from .forms import LoginForm, ForgetForm, ModifyPwdForm, ModifyUserForm, ModifyUserProfileForm
from django.db.models import Q
from .models import EmailVerifyRecord, UserProfile
from django.utils import timezone
import datetime
from utils.email_send import send_resetpwd_mail
from django.contrib.auth.hashers import make_password
from django.contrib.auth.decorators import login_required   # django鉴权模块

# Create your views here.

class MyBackend(ModelBackend):
    """ 重写django身份验证后端，实现邮箱登录 """
    def authenticate(self, request, username=None, password=None, **kwargs):
        try:
            user = User.objects.get(Q(username=username) | Q(email=username))
            if user.check_password(password):
                return user
        except Exception as e:
            return None


def login_view(request):
    """ 登录视图 """
    if request.method != 'POST':
        # 不是POST请求就获取空表单
        form = LoginForm()
    else:
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = authenticate(request, username=username, password=password)
           
            if user is not None:
                login(request, user)
                return redirect('/')
            else:
                return HttpResponse('登录失败')
    
    return render(request, 'users/login.html', context={'form': form})


def forget_pwd(request):
    """ 忘记密码 """
    if request.method != 'POST':
        form = ForgetForm()
    else:
        form = ForgetForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']

            exist = User.objects.filter(email=email).exists()
            if exist:
                send_resetpwd_mail(email)
                return render(request, 'users/forget.html', {'form': form, 'msg': '邮件已发送，请注意查收。'})
            else:
                err_info = '该邮箱未注册！请检查输入是否有误。'
                return render(request, 'users/forget.html', {'form': form, 'err_info': err_info})
    return render(request, 'users/forget.html', {'form': form})


def logout_view(request):
    """ 退出登录 """
    logout(request)
    return redirect('users:login')


def reset_pwd(request, code=None):
    """ 重置密码 """
    record = EmailVerifyRecord.objects.get(code=code)
    # 判断是否在一个小时内点击链接
    if code is not None and timezone.now()-record.ge_date < datetime.timedelta(hours=1):
        if request.method != 'POST':
            form = ModifyPwdForm()
            return render(request, 'users/reset_pwd.html', {'form': form})
        else:
            form = ModifyPwdForm(request.POST)
            if form.is_valid():
                email = record.email
                user = User.objects.get(email=email)
                user.password = make_password(form.cleaned_data.get('password'))
                user.save()
                return HttpResponse('密码修改成功！')
            else:
                return HttpResponse("密码修改失败！")
    else:
        return HttpResponse('链接超时！')


@login_required(login_url='users:login')
def reset_pwd_inner(request):
    """ 登录后在个人主页重置密码 """
    user = User.objects.get(id=request.user.id)
    if request.method != 'POST':
        form = ModifyPwdForm()
        return render(request, 'users/reset_pwd.html', {'form': form})
    else:
        form = ModifyPwdForm(request.POST)
        if form.is_valid():
            user.password = make_password(form.cleaned_data.get('password'))
            user.save()
            return HttpResponse('密码修改成功！')
        else:
            return HttpResponse("密码修改失败！")


# 如果没有登录，跳转到登录界面
@login_required(login_url='users:login')
def user_profile(request):
    """ 用户信息展示 """
    user = User.objects.get(username=request.user)
    return render(request, 'users/user_profile.html', {'user': user})


@login_required(login_url='users:login')
def editor_users(request):
    """ 修改用户信息 """
    user = User.objects.get(id=request.user.id)

    if request.method == 'POST':
        try:
            # 如果userprofile存在
            user_profile = user.userprofile
            # 获取表单数据
            user_form = ModifyUserForm(request.POST, instance=user)
            userprofile_form = ModifyUserProfileForm(request.POST, request.FILES, instance=user_profile)
            # 保存
            if user_form.is_valid() and userprofile_form.is_valid():
                user_form.save()
                userprofile_form.save()
                # 转到个人信息展示页面
                return redirect('users:user_profile')
        except UserProfile.DoesNotExist:
            # 该用户在userprofile表中还没有对应的数据

            # 获取表单信息
            user_form = ModifyUserForm(request.POST, instance=user)
            userprofile_form = ModifyUserProfileForm(request.POST, request.FILES)
            # 保存
            if user_form.is_valid() and userprofile_form.is_valid():
                user_form.save()
                # commit=False 先不保存，放在内存中，然后再重新给指定字段赋值
                new_userprofile = userprofile_form.save(commit=False)
                new_userprofile.owner = request.user
                new_userprofile.save()
                return redirect('users:user_profile')
    else:
        try:
            user_profile = user.userprofile
            user_form = ModifyUserForm(instance=user)
            userprofile_form = ModifyUserProfileForm(instance=user_profile)
        except UserProfile.DoesNotExist:
            user_form = ModifyUserForm(instance=user)
            userprofile_form = ModifyUserProfileForm()
    return render(request, 'users/editor_users.html', locals())

myblog/users/templates/users/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width-device-width,initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="sie-edge" />
    <link rel="stylesheet" type="text/css" href="{% static 'users/css/login.css' %}">

    {% block head %}
    {% endblock %}
</head>

<body style="background-image: url({% static 'users/image/bg.png' %});">
    <div class="container" id="container">
        <div class="form-container sign-in-container">
            {% block content %}

            {% endblock%}
        </div>
    </div>
</body>

</html>

myblog/users/templates/users/editor_users.html
{% extends 'users/user_profile.html' %}
{% block title %}
<li class="is-active is-size-5 has-text-weight-bold"><span>修改用户信息</span></li>
{% endblock %}

{% block content %}
<form action="{% url 'users:editor_users' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {% for field in user_form %}
    <div class="field is-horizontal">
        <div class="field-label is-normal">
            <label for="{{ field.id_for_label }}" class="label">{{ field.label }}</label>
        </div>
        <div class="field-body">
            <div class="field">
                <div class="control">
                    {{ field }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    {% for field in userprofile_form %}
    <div class="field is-horizontal">
        <div class="field-label is-normal">
            <label for="{{ field.id_for_label }}" class="label">{{ field.label }}</label>
        </div>
        <div class="field-body">
            <div class="field">
                <div class="control">
                    {{ field }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <input class=" button is-primary is-pulled-right" type="submit" value="保存修改">
    <div class=" is-clearfix"></div>

</form>
{% endblock %}

myblog/users/templates/users/forget.html
{% extends 'users/base.html' %}

{% block head %}
    <title>找回密码</title>
{% endblock %}


{% block content %}
    <form action="#" method="post">
        {% csrf_token %}
        <h1>找回密码</h1>
        {{ form.as_p }}

        {% if err_info %}
            <p style="color: red;">{{ err_info }}</p>
        {% elif msg %}
            <span>{{ msg }}</span>
        {% endif %}
        <input type="submit" value="提交">
    </form>
{% endblock %}

myblog/users/templates/users/login.html
{% extends 'users/base.html' %}

{% block head %}
<title>登录</title>
{% endblock %}

{% block content %}

    <form action="#", method="post">
        <h1>登录</h1>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="登录">
        <a href="{% url 'users:forget_pwd' %}"><span>忘记密码</span></a>
    </form>

{% endblock %}

myblog/users/templates/users/reset_pwd.html
{% extends 'users/base.html' %}

{% block head %}
    <title>重置密码</title>
{% endblock %}

{% block content %}
    <form action="" method="post">
        <h1>重置密码</h1>
        {% csrf_token %}
        {{ form.as_p }}
        {{ form.errors }}
        <input type="submit" value="重置密码">
    </form>
{% endblock %}

myblog/users/templates/users/user_profile.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>个人中心</title>

    <!-- bulma -->
    <link rel="stylesheet" href="{% static 'users/css/bulma.css' %}">
    <!-- jquery -->
    <script src="{% static 'users/js/jquery-3.6.0.min.js' %}"></script>
    <!-- 使bulma下拉组件（Dropdown）生效的js文件 -->
    <!-- <script src="{% static 'users/js/dropdown.js' %}"></script> -->

    <!-- 自定义样式 -->
    <link rel="stylesheet" href="{% static 'users/css/style.css' %}">

    <!-- 引入阿里图标库 -->
    <link rel="stylesheet" href="//at.alicdn.com/t/font_3273978_ic93w3ru5jj.css">
</head>

<body>
    <!-- 头部导航 -->
    <nav class="navbar is-dark">
        <div class="container">
            <!-- logo -->
            <div class="navbar-brand">
                <a href="\" class="navbar-item">
                    <img src="{% static 'users/image/logo.png' %}" width="112" height="28" alt="logo">
                </a>
                <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false"
                    data-target="navbarBasicExample">
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                </a>
            </div>
            <!-- 头像、用户名及下拉菜单 -->
            <div id="navbarBasicExample" class="navbar-menu">
                <div class="navbar-end">
                    <div class="navbar-item">
                        <!-- 头像 -->
                        <figure class="image is-24x24 mr-2">
                            {% if user.userprofile.image %}
                            <img class="is-rounded" src="{{ MEDIA_URL }}{{ user.userprofile.image }}" alt="" srcset="">
                            {% else %}
                            <img class="is-rounded" src="{% static 'users/image/default.png' %}" alt="" srcset="">
                            {% endif %}
                        </figure>
                    </div>
                    <!-- 用户名及下拉菜单 -->
                    <div class="navbar-item ml-0 pl-0">
                        <div class="dropdown is-hoverable">
                            <div class="dropdown-trigger">
                                <a>
                                    <span class="has-text-light is-size-6">{{ user.username }}</span>
                                </a>
                                <span class="iconfont icon-unfold"></span>
                            </div>
                            <div class="dropdown-menu" id="dropdown-menu2" role="menu">
                                <div class="dropdown-content is-shadowless">
                                    <div class="dropdown-item">
                                        <a class="has-text-grey-dark" href="{% url 'blog:index' %}">
                                            <span class="iconfont icon-home"></span>&nbsp;&nbsp;
                                            博客主页
                                        </a>
                                    </div>
                                    <div class="dropdown-item">
                                        <a class=" has-text-grey-dark" href="{% url 'users:editor_users' %}">
                                            <span class="iconfont icon-setup_fill"></span>&nbsp;&nbsp;
                                            修改账户信息
                                        </a>
                                    </div>
                                    <div class="dropdown-item">
                                        <a class=" has-text-grey-dark" href="{% url 'users:reset_pwd_inner' %}">
                                            <span class="iconfont icon-icon-test1"></span>&nbsp;&nbsp;
                                            重置密码
                                        </a>
                                    </div>
                                    <hr class="dropdown-divider">
                                    <div class="dropdown-item">
                                        <a class=" has-text-grey-dark" href="{% url 'users:logout' %}">
                                            <span class="iconfont icon-undo"></span>&nbsp;&nbsp;
                                            退出登录
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </nav>

    <!-- 页面主体 -->
    <section class="section">
        <div class="container">
            <div class="columns">
                <!-- 左侧菜单 -->
                <div class="column is-2">
                    <div class="card">
                        <header class="card-header">
                            <p class="card-header-title">个人中心</p>
                            <a href="" class="card-header-icon" aria-label="more options">
                                <span class="iconfont icon-unfold"></span>
                            </a>
                        </header>
                        <div class="card-content menu">
                            <ul class="content menu-list">
                                <li><a href="{% url 'users:user_profile' %}">个人信息</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="card">
                        <header class="card-header">
                            <p class="card-header-title">内容管理</p>
                            <a href="#" class="card-header-icon" aria-label="more options">
                                <span class="iconfont icon-unfold"></span>
                            </a>
                        </header>
                        <div class="card-content menu">
                            <ul class="content menu-list">
                                <li><a href="">添加文章</a></li>
                                <li><a href="">已发布</a></li>
                                <li><a href="">草稿箱</a></li>
                                <li><a href="">评论管理</a></li>
                                <li><a href="">数据分析</a></li>
                            </ul>
                        </div>

                    </div>
                </div>

                <!-- 右侧显示用户信息部分 -->
                <div class="column is-10">
                    <div class="box is-radiusless is-shadowless">
                        <div class="tabs">
                            <ul>
                                {% block title %}
                                <li class="is-active is-size-5 has-text-weight-bold"><span>用户信息</span></li>
                                {% endblock %}
                            </ul>
                        </div>

                        {% block content %}
                        <div class="columns is-mobile" style="border-bottom: #ededed solid 1px; padding-bottom: 1rem">
                            <div class="column is-narrow">
                                <figure class="image is-96x96">

                                    {% if user.userprofile.image %}
                                    <img class="is-rounded" src="{{ MEDIA_URL }}{{ user.userprofile.image }}">
                                    {% else %}
                                    <!-- 如果没有关联对象，显示默认头像 -->
                                    <img class="is-rounded" src=" {% static 'users/image/default.png' %}">
                                    {% endif %}
                                </figure>
                            </div>
                            <div class="column is-narrow">
                                <div style="padding-top: 1.5rem;">

                                    {% if user.userprofile.nickname %}
                                    <h1 class="title is-size-4">{{ user.userprofile.nickname }}</h1>
                                    {% else %}
                                    <h1 class="title is-size-4">{{ user.username }}</h1>
                                    {% endif %}


                                    {% if user.userprofile.sign %}
                                    <p class="subtitle is-size-6">{{ user.userprofile.sign }}</p>
                                    {% else %}
                                    <p class="subtitle is-size-6">这个人很懒，什么都没有写。。</p>
                                    {% endif %}
                                </div>
                            </div>
                        </div>

                        <div class="columns" style="padding:1rem 0; ">
                            <div class="column is-2">
                                <p>个人信息</p>
                            </div>
                            <div class="column">
                                <div class="columns is-mobile" style="border-bottom: #ededed solid 1px">
                                    <div class="column is-2">
                                        <span class=" has-text-grey-light">用户名</span>
                                    </div>
                                    <div class="column is-narrow">
                                        <span class=" has-text-black-ter">{{ user.username }}</span>
                                    </div>
                                </div>
                                <div class="columns is-mobile" style="border-bottom: #ededed solid 1px">
                                    <div class="column is-2">
                                        <span class=" has-text-grey-light">邮箱</span>
                                    </div>
                                    <div class="column is-narrow">
                                        <span class=" has-text-black-ter">{{ user.email }}</span>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="columns" style="padding:1rem 0; ">
                            <div class="column is-2">
                                <p>个人简介</p>
                            </div>
                            <div class="column">
                                <div class="content">
                                    {% if user.userprofile.desc %}
                                    {{ user.userprofile.desc }}
                                    {% else %}
                                    暂未设置
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        {% endblock %}
                    </div>
                </div>
            </div>
        </div>
    </section>
    </div>
    </nav>
</body>

</html>