myblog/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<int:post_id>/', views.post_detail, name='post_detail'),
    path('search/', views.search, name='search'),
    path('archives/<int:year>/<int:month>/', views.archives, name='archives'),
    path('add_post/', views.add_post, name='add_post')
]

myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from utils.upload import upload_file


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('blog.urls')),
    # path('uploads/', upload_file, name='uploads')   # 上传图片url
    path('ckeditor/', include('ckeditor_uploader.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myblog/users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path('login/', views.login_view, name="login"),
    path('forget_pwd/', views.forget_pwd, name='forget_pwd'),
    path('logout/', views.logout_view, name='logout'),
    path('reset_pwd/<code>/', views.reset_pwd, name='reset_pwd'),
    path('reset_pwd_inner/', views.reset_pwd_inner, name='reset_pwd_inner'),
    path('user_profile/', views.user_profile, name='user_profile'),
    path('editor_users/', views.editor_users, name='editor_users')
]

myblog/blog/models.py
from django.db import models
from django.template.loader import render_to_string
# from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

class Category(models.Model):
    """ 博客分类模型 """
    name = models.CharField(max_length=32, verbose_name='分类名称')
    desc = models.TextField(max_length=200, blank=True, default='', verbose_name='分类描述')
    add_date = models.DateField(auto_now=True, verbose_name="添加日期")
    mod_date = models.DateField(auto_now=True, verbose_name="修改日期")

    class Meta:
        verbose_name = "博客分类"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Tag(models.Model):
    """ 文章标签模型 """
    name = models.CharField(max_length=10, verbose_name='文章标签')
    add_date = models.DateField(auto_now=True, verbose_name="添加日期")
    mod_date = models.DateField(auto_now=True, verbose_name="修改日期")

    class Meta:
        verbose_name = "文章标签"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Post(models.Model):
    """ 文章模型 """
    title = models.CharField(max_length=60, verbose_name="文章标题")
    desc = models.TextField(max_length=200, blank=True, default='', verbose_name='文章描述')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='文章分类')
    # content = models.TextField(verbose_name="文章详情")
    # content = RichTextField(verbose_name="文章详情")
    content = RichTextUploadingField(verbose_name="文章详情")
    tags = models.ForeignKey(Tag, blank=True, null=True, on_delete=models.CASCADE, verbose_name='文章标签')
    pv = models.IntegerField(default=0, verbose_name="浏览量")
    add_date = models.DateField(auto_now=True, verbose_name="添加日期")
    mod_date = models.DateField(auto_now=True, verbose_name="修改日期")

    class Meta:
        verbose_name = "文章"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title


class Sidebar(models.Model):
    """ 侧边栏 """
    STATUS = (
        (1, '隐藏'),
        (2, '展示')
    )

    DISPLAY_TYPE = (
        (1, '搜索'),
        (2, '最新文章'),
        (3, '最热文章'),
        (4, '最近评论'),
        (5, '文章归档'),
        (6, 'HTML')
    )

    title = models.CharField(max_length=50, verbose_name="模块名称")  # 模块名称
    display_type = models.PositiveIntegerField(default=1, choices=DISPLAY_TYPE,
                                               verbose_name="展示类型")  # 侧边栏  搜索框/最新文章/热门文章/HTML自定义等
    content = models.CharField(max_length=500, blank=True, default='', verbose_name="内容",
                               help_text="如果设置的不是HTML类型，可为空")  # 这个字段是专门用来给HTML类型用的，其他类型可为空
    sort = models.PositiveIntegerField(default=1, verbose_name="排序", help_text='序号越大越靠前')
    status = models.PositiveIntegerField(default=2, choices=STATUS, verbose_name="状态")  # 隐藏  显示状态
    add_date = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")  # 时间

    class Meta:
        verbose_name = "侧边栏"
        verbose_name_plural = verbose_name
        ordering = ['-sort']

    @classmethod
    def get_sidebar(cls):
        # 查询到所有允许展示的模块
        return cls.objects.filter(status=2)

    @property  # 成为一个类属性，调用的时候不需要后边的（）,是只读的，用户没办法修改
    def get_content(self):
        if self.display_type == 1:
            context = {

            }
            return render_to_string('blog/sidebar/search.html', context=context)
        elif self.display_type == 2:
            context = {

            }
            return render_to_string('blog/sidebar/new_post.html', context=context)
        elif self.display_type == 3:
            context = {

            }
            return render_to_string('blog/sidebar/hot_post.html', context=context)
        elif self.display_type == 4:
            context = {

            }
            return render_to_string('blog/sidebar/commment.html', context=context)
        elif self.display_type == 5:  # 文章归档
            context = {

            }
            return render_to_string('blog/sidebar/archives.html', context=context)
        elif self.display_type == 6:  # 自定义侧边栏

            return self.content  # 在侧边栏直接使用这里的html，模板中必须使用safe过滤器去渲染HTML

myblog/blog/views.py
from django.shortcuts import render, get_object_or_404, HttpResponse
from .models import Category, Post, Tag
from django.db.models import Q, F
from django.core.paginator import Paginator


def index(request):
    """ 博客主页视图 """
    post_list = Post.objects.all()

    # 分页方法, 每页显示10条
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'blog/index.html', {'page_obj': page_obj})


def post_detail(request, post_id):
    """ 博客详情页视图 """
    # post_id对应的博客模型对象
    post = get_object_or_404(Post, id=post_id)

    # 刷新一次浏览量就加一
    Post.objects.filter(id=post_id).update(pv=F('pv')+1)

    # 前一篇的博文 id__lt=post_id  id>post_id last()查询最后一个对象
    prev_post = Post.objects.filter(id__lt=post_id).last()
    # 后一篇的博文
    next_post = Post.objects.filter(id__gt=post_id).first()

    return render(request, 'blog/detail.html', locals())


def search(request):
    """ 搜索视图 """
    # 获取表单
    keyword = request.GET.get('keyword')
    if not keyword:  # 如果没有搜索，显示所有的文章
        post_list = Post.objects.all()
    else:
        # 如果标题、描述、内容里包含所搜索的关键字，则显示出来
        post_list = Post.objects.filter(
            Q(title__icontains=keyword) | Q(desc__icontains=keyword) | Q(content__icontains=keyword))

    content = {
        'post_list': post_list
    }
    # 和首页保持一致
    return render(request, 'blog/index.html', content)


def archives(request, year, month):
    """ 文章归档视图 """
    # 按年和月筛选文章
    post_list = Post.objects.filter(add_date__year=year, add_date__month=month)

    context = {
        "year": year,
        "month": month,
        "post_list": post_list
    }
    return render(request, 'blog/archives_list.html', context=context)


def add_post(request):
    return render(request, 'blog/add_post.html')

myblog/blog/templates/blog/add_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div id="toolbar-container"></div>
<div id="editor-container"></div>
</body>
</html>

myblog/blog/templates/blog/archives_list.html
{% extends 'blog/base.html' %}

{% block title %}
    {{ year }}年{{ month }}月的文章
{% endblock %}

{% block right %}
    <div class="box is-shadowless is-radiusless">
        每月归档，{{ year }}年{{ month }}月
        <div class="tags has-addons is-pulled-right">
            <span class="tag">共</span>
            <span class="tag is-primary">{{ post_list.count }}篇</span>
        </div>
    </div>

    {# 继承模板中原有内容 #}
    {{ block.super }}
{% endblock %}

myblog/blog/templates/blog/base.html
<!DOCTYPE html>
{% load static category %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <!-- 导入bulma -->
    <link rel="stylesheet" href="{% static 'users/css/bulma.css' %}">
    <!-- jquery -->
    <script src="{% static 'users/js/jquery-3.6.0.min.js' %}"></script>

    <!-- 引入阿里图标库 -->
    <link rel="stylesheet" href="//at.alicdn.com/t/font_3273978_ic93w3ru5jj.css">

    <!---->
    <script src="{% static 'ckeditor/ckeditor/plugins/prism/lib/prism/prism_patched.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'ckeditor/plugins/prism/prism.css' %}">
    <title>
        {% block title %}
        {% endblock %}
    </title>

</head>

<body>

<!-- 导航条 -->
<div class="pt-6" style="margin-top: 30px;">
    <nav class="navbar is-black container" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <a class="navbar-item" href="{% url 'blog:index' %}">
                <img src="{% static 'users/image/logo.png' %}" width="112" height="28">
            </a>

            <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false"
               data-target="navbarBasicExample">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>
        </div>

        <div id="navbarBasicExample" class="navbar-menu">
            <div class="navbar-start">
                {% block navbar-start %}
                    <a class="navbar-item" href="/">
                        博客主页
                    </a>
                    <div class="navbar-item has-dropdown is-hoverable">
                        <a class="navbar-link">
                            博客分类
                        </a>
                        <div class="navbar-dropdown">
                            {% get_category_list as category_list %}
                            {% for category in category_list %}
                                <a class="navbar-item">
                                    {{ category.name }}
                                </a>
                            {% endfor %}
                        </div>
                    </div>
                {% endblock %}
            </div>

            <div class="navbar-end">
                {% block navbar-end %}
                    <!-- 判断是否登录 -->
                    {% if user.is_authenticated %}
                        <div class="navbar-item">
                            <!-- 头像 -->
                            <div class="narbar-item">
                                <figure class="image is-24x24 mr-2">
                                    {% if user.userprofile.image %}
                                        <img class="is-rounded" src="{{ MEDIA_URL }}{{ user.userprofile.image }}" alt=""
                                             srcset="">
                                    {% else %}
                                        <img class="is-rounded" src="{% static 'users/image/default.png' %}" alt=""
                                             srcset="">
                                    {% endif %}
                                </figure>
                            </div>
                            <!-- 用户名及下拉菜单 -->
                            <div class="navbar-item">
                                <div class="dropdown is-hoverable">
                                    <div class="dropdown-trigger">
                                        <a>
                                            <span class="has-text-light is-size-6">{{ user.username }}</span>
                                        </a>
                                        <span class="iconfont icon-unfold"></span>
                                    </div>
                                    <div class="dropdown-menu" id="dropdown-menu2" role="menu">
                                        <div class="dropdown-content is-shadowless">
                                            <div class="dropdown-item">
                                                <a class="has-text-grey-dark" href="{% url 'users:user_profile' %}">
                                                    <span class="iconfont icon-icon-test"></span>&nbsp;&nbsp;
                                                    个人中心
                                                </a>
                                            </div>
                                            <div class="dropdown-item">
                                                <a class="has-text-grey-dark" href="{% url 'admin:index' %}">
                                                    <span class="iconfont icon-Admin-01"></span>&nbsp;&nbsp;
                                                    管理后台
                                                </a>
                                            </div>
                                            <hr class="dropdown-divider">
                                            <div class="dropdown-item">
                                                <a class="has-text-grey-dark" href="{% url 'blog:add_post' %}">
                                                    <span class="iconfont icon-Admin-01"></span>&nbsp;&nbsp;
                                                    添加新文章
                                                </a>
                                            </div>
                                            <hr class="dropdown-divider">
                                            <div class="dropdown-item">
                                                <a class=" has-text-grey-dark" href="{% url 'users:logout' %}">
                                                    <span class="iconfont icon-undo"></span>&nbsp;&nbsp;
                                                    注销登录
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% else %}
                        <!-- 登录按钮 -->
                        <div class="navbar-item">
                            <div class="buttons">
                                <!-- target="_blank"  打开新页面 -->
                                <a class="button is-dark is-rounded" href="{% url 'users:login' %}" target="_blank"
                                   title="点这里，登录滴干活">
                                    <span class="iconfont icon-icon-test" style="font-size: 24px"></span>
                                </a>
                            </div>
                        </div>
                    {% endif %}
                {% endblock %}
            </div>
        </div>
    </nav>
</div>

<!-- 主要内容显示部分 -->
<section class="section">
    <div class="container">
        <div class="columns">
            <!-- 左侧 -->
            <div class="column is-9">
                {% block left %}
                    左侧
                {% endblock %}
            </div>

            <!-- 右侧 -->
            <div class="column is-3">
                {% block right %}
                    {% get_sidebar_list as sidebar_list %}
                    {% for sidebar in sidebar_list %}
                        <div class="box">
                            <h1 class=" is-size-5 title">{{ sidebar.title }}</h1>
                            <p>{{ sidebar.get_content|safe }}</p>
                        </div>
                    {% endfor %}
                {% endblock %}
            </div>
        </div>
    </div>
</section>

<!-- 页脚 -->
<footer class="footer container has-narbar-fixed-bottom">
    <div class="content has-text-centered">
        <p>
            <strong>Bulma</strong> by <a href="https://jgthms.com">Jeremy Thomas</a>. The source code is licensed
            <a href="http://opensource.org/licenses/mit-license.php">MIT</a>. The website content
            is licensed <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY NC SA 4.0</a>.
        </p>
    </div>
</footer>
</body>

</html>

myblog/blog/templates/blog/detail.html
{% extends 'blog/base.html' %}

{% block left %}
    <div class="box">
        <h1 class="is-size-5  has-text-weight-bold">{{ post.title }}</h1>
        <div class="is-size-7 has-text-grey-light pt-1 pb-1">
            <span>发布日期：{{ post.add_date }}</span>
        </div>
        <div class="content">
            {{ post.content | safe }}
        </div>
    </div>
    <div class="box">
        <div class="level is-size-7">
            <div class="level-left">
                {# 如果prev_post.id存在，显示上一篇 #}
                {% if prev_post %}
                    <span>上一篇：</span>
                    <a href="{% url 'blog:post_detail' prev_post.id %}" class="level-item">{{ prev_post.title }}</a>
                {% endif %}
            </div>
            <div class="level-right">
                {% if next_post %}
                    <span>下一篇：</span>
                    <a href="{% url 'blog:post_detail' next_post.id %}" class="level-item">{{ next_post.title }}</a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

myblog/blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% block title %}
Charramma的个人博客
{% endblock %}

{% block left %}
{% if page_obj %}
<!-- 博客列表 -->
{% for post in page_obj %}
<div class="box">
    <h1 class="is-size-5  has-text-weight-bold"><a href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</a></h1>
    <div class="is-size-7 has-text-grey-light pt-1 pb-1">
        <span>发布日期：{{ post.add_date }}</span>
    </div>
    <!-- 显示博客描述 -->
    <!-- truncatechars 控制文章描述显示字数，只显示50个字节 -->
    <p class="mt-3 is-size-6">&nbsp;&nbsp;{{ post.desc|truncatechars:50 }}</p>
</div>
{% endfor %}
<!-- 分页按钮 -->
<nav class="pagination is-rounded" role="navigation" aria-label="pagination">
    <!-- 如果存在上一页 -->
    {% if page_obj.has_previous %}
    <a class="pagination-previous" href="?page={{ page_obj.previous_page_number }}"><span
            class="iconfont icon-angle-double-left"></span></a>
    {% endif %}
    <!-- 如果存在下一页 -->
    {% if page_obj.has_next %}
    <a class="pagination-next" href="?page={{ page_obj.next_page_number }}"><span
            class="iconfont icon-angle-double-right"></span></a>
    {% endif %}
    <!-- 如果只有一页，不显示页码 -->
    {% if page_obj.paginator.num_pages > 1 %}
    <ul class="pagination-list">
        {% if page_obj.has_previous %}
        <li><a class="pagination-link" href="?page={{ page_obj.previous_page_number }}"
                aria-label="Goto page {{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
        </li>
        {% endif %}
        <li><a class="pagination-link is-current" aria-label="Page {{ page_obj.number }}" aria-current="page"
                href='?page={{ page_obj.number }}'>{{ page_obj.number }}</a>
        </li>
        {% if page_obj.has_next %}
        <li><a class="pagination-link" href="?page={{ page_obj.next_page_number }}"
                aria-label="Goto page {{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
        </li>
        {% endif %}
    </ul>
    {% endif %}
</nav>
{% else %}
<div class="box">
    <p class="mt-3 is-size-6">没有相关文章...</p>
</div>
{% endif %}

{% endblock %}